name: GitHub-Profile-3D-Contrib

on:
  schedule: # 03:00 JST == 18:00 UTC
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v2
      - uses: yoshi389111/github-profile-3d-contrib@0.6.0
        env:
          GITHUB_TOKEN: ${{ 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 }}
          USERNAME: ${{ uiseongsnag }}
      - name: Commit & Push
        run: |
          git config user.name uiseongsang
          git config user.email yixing93@naver.com
          git add -A .
          git commit -m "generated"
          git push
